meta:
  title: Portal Adventure
  description: Developer portals done right
  siteUrl: https://portal-adventure.redoc.ly
  keywords: redocly developer portal, api portal starter, api reference docs
  lang: en-US
linkChecker:
  severity: warning
  options:
    CheckExternal: true
logo:
  image: ./images/logo.png
  altText: Redocly Logo
toc:
  enable: true
oasDefinitions:
  xkcd1: https://api.redocly.com/registry/bundle/lorna_testing/XKCD/v1/openapi.yaml?branch=main
  xkcd2: https://api.redocly.com/registry/bundle/lorna_testing/XKCD/v2/openapi.yaml?branch=main
stylesheets:
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
  - https://fonts.googleapis.com/css?family=Source+Code+Pro:300,400,600,700&display=swap
#analytics:
  # ga:
  # note that GA doesn't work in the development environment
  #  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:
  - label: Home
    page: /index.md

  - label: Quick links
    page: /quicklinks.md

  - label: External docs
    icon: ./images/redocly-icon-white.png
    href: https://redoc.ly/docs/developer-portal/introduction/

  - search: true

footer:
  copyrightText: Copyright Â© Redocly 2019-2021. All right reserved.
  columns:
    - group: Source
      items:
        - label: GitHub
          page: https://github.com/lornajane/portal-adventure
            
    - group: About
      items:
        - label: Contact
          page: contact.mdx
